bsp_output_dir: writing/fupugecscore/data/output/basic_score  # The output directory where the basic score model checkpoints will be written or loaded
csp_output_dir: writing/fupugecscore/data/output/coherence_score  # The output directory where the coherence score model checkpoints will be written or loaded
psp_output_dir: writing/fupugecscore/data/output/prompt_score  # The output directory where the prompt-relevant score model checkpoints will be written or loaded
osp_output_dir: writing/fupugecscore/data/output/overall_score  # The output directory of overall score model(xgboost)
data_dir: writing/fupugecscore/data/train_data # The input data dir for train and eval.
bert_dir: writing/fupugecscore/data/uncased_L-12_H-768_A-12  # The pre-trained bert-original model dir
bert_emb_dim: 768  # the embedding dim of bert model

advanced_word_path: writing/fupugecscore/resources/advanced_words
